/**
 * @author konqueror7
 *
 * Problem:
 *  Each new term in the Fibonacci sequence is generated by adding the previous
 *  two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 *      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 *  By considering the terms in the Fibonacci sequence whose values do not
 *  exceed four million, find the sum of the even-valued terms.
 *
 * Answer:
 *  4613732
 */

object Problem2 {
	def main(args : Array[String]) = {
		val LIMIT = 4000000
		var sumEven = 0
		var count = 0
		var fibVal = 0

		while ({ count += 1; fibVal = fibonacci(count); fibVal <= LIMIT }) {
			if ((fibVal % 2) == 0)
				sumEven += fibVal
		}
		print(sumEven)
	}

	def fibonacci(n : Int) : Int = {
		if (n <= 1)
			return n
		else
			return fibonacci(n - 1) + fibonacci(n - 2);
	}
}